.PHONY: build test badge help

help: ## Show all available options
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

# Detect if a specific service is passed
SERVICE ?=

services: ## Builds all services from the repository or a specific one with SERVICE=name
ifeq ($(SERVICE),)
	@.scripts/services.sh -a
else
	@.scripts/services.sh -s $(SERVICE)
endif

test: ## Executes unit tests from all services from the repository or a specific one with SERVICE=name
ifeq ($(SERVICE),)
	@.scripts/tests.sh -a
else
	@.scripts/tests.sh -s $(SERVICE)
endif

badges: ## Updates badges of all services from the repository or a specific one with SERVICE=name
ifeq ($(SERVICE),)
	@.scripts/badges.sh -a
else
	@.scripts/badges.sh -s $(SERVICE)
endif